public class code3 {
    public static void main(String[] args) {
        try
        {
            int[] value = new int[3];
            value[4]=10;
            int data=12/0;
            System.out.println("throws exception");
        }
catch(ArrayIndexOutOfBoundsException e)
        {
            System.out.println(e);
        }
        catch(ArithmeticException e)
        {
            System.out.println(e);
        }
    
        catch(Exception e)
        {
            System.out.println(e);
        }
        System.out.println("code executed");
    }
}
